I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 78, in script
    jump test1thr
ScriptError: could not find label 'test1thr'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 78, in script
    jump test1thr
  File "/home/jrcarguy11/renpy-8.3.7-sdk/renpy/ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "/home/jrcarguy11/renpy-8.3.7-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'test1thr'.

Linux-6.6.76-g027a1f314c8f-x86_64-with-glibc2.36 x86_64
Ren'Py 8.3.7.25031702
Echo Chaser 0.2
Wed Apr 23 09:26:40 2025
